create table if not exists public.receipts (
  id bigint generated by default as identity primary key,
  supplier text not null,
  product text not null,
  quantity numeric(12, 2) not null check (quantity >= 0),
  unit text not null,
  price numeric(12, 2) not null check (price >= 0),
  vehicle text not null default '',
  note text not null default '',
  source text not null default 'dashboard',
  status text not null default 'Noua',
  received_by text not null default '',
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz
);

create index if not exists receipts_created_at_idx on public.receipts (created_at desc);
create index if not exists receipts_status_idx on public.receipts (status);
